name: Node.js CI/CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci
        working-directory: server # Ensure npm install runs in the 'server' folder

      - name: Create .env File
        run: |
          touch .env
          echo "TWILIO_PHONE_NUMBER=${{ secrets.TWILIO_PHONE_NUMBER }}" > .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "GMAIL_USER=${{ secrets.GMAIL_USER }}" >> .env
          echo "GMAIL_PASS=${{ secrets.GMAIL_PASS }}" >> .env
          echo "TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}" >> .env
          echo "TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}" >> .env

        working-directory: server # Ensure .env file is created in the 'server' folder

      - name: Restart API
        run: pm2 restart api
        working-directory: ./server
