name: Node.js CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Check current directory
        run: pwd # This will log the current working directory

      - run: npm install
        working-directory: ./server # Ensure npm install runs in the 'server' folder

      - name: Log current directory after npm install
        run: pwd # Log again to verify the directory after the install

      - run: |
          touch .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
          echo "GMAIL_USER=${{ secrets.GMAIL_USER }}" >> .env
          echo "GMAIL_PASS=${{ secrets.GMAIL_PASS }}" >> .env
          echo "TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}" >> .env
          echo "TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}" >> .env
          echo "TWILIO_PHONE_NUMBER=${{ secrets.TWILIO_PHONE_NUMBER }}" >> .env
        working-directory: ./server # Ensure .env file is created in the 'server' folder

      - name: Check current directory before restarting
        run: pwd # Log before restarting to verify the directory


      # - run: pm2 restart api
      #   working-directory: ./server # Uncomment this if you need to restart using pm2
